# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FBLA Mobile Application’ do
	
	pod 'Firebase/Auth'
	pod ‘Firebase/Storage’
	pod ‘Firebase/Database’

end